services:
  ai-streaming-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app/src
      # Custom Model Configuration (uncomment and modify to use a different model locally)
      # Lightweight options
      # - MODEL_NAME=distilgpt2              # ~82M params - Fast, minimal memory
      # - MODEL_NAME=gpt2                    # ~124M params - Original GPT-2 small
      - MODEL_NAME=HuggingFaceTB/SmolLM-135M # ~135M params - Efficient small model
      # Medium options
      # - MODEL_NAME=gpt2-medium # ~355M params - Better quality, more memory
      # - MODEL_NAME=microsoft/DialoGPT-small  # ~117M params - Conversation focused
      # - MODEL_NAME=HuggingFaceTB/SmolLM-360M # ~360M params - Efficient small model
      # - MODEL_NAME=Qwen/Qwen2.5-0.5B-Instruct # ~500M params - Instruction-tuned model
      # Large options
      # - MODEL_NAME=gpt2-large # ~774M params - High quality, high memory
      # - MODEL_NAME=HuggingFaceTB/SmolLM2-1.7B # ~1.7B params - high quality, high memory

      # CORS Configuration (uncomment and modify for production testing)
      # - FRONTEND_URL=http://localhost:8000
      # - ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
    volumes:
      # Mount the source code for development (optional)
      - ./src:/app/src:ro
      # Persist Hugging Face model cache
      - huggingface_cache:/home/appuser/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Optional: Add a reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-streaming-app
    restart: unless-stopped
    profiles:
      - production

volumes:
  huggingface_cache:
    driver: local

networks:
  default:
    name: ai-streaming-network
