services:
  ai-streaming-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app/src
      # Custom Model Configuration (uncomment and modify to use a different model locally)
      # - MODEL_NAME=microsoft/DialoGPT-small
      # - MODEL_NAME=gpt2
      # - MODEL_NAME=distilgpt2
      # CORS Configuration (uncomment and modify for production testing)
      # - FRONTEND_URL=http://localhost:8000
      # - ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
    volumes:
      # Mount the source code for development (optional)
      - ./src:/app/src:ro
      # Persist Hugging Face model cache
      - huggingface_cache:/home/appuser/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    
  # Optional: Add a reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-streaming-app
    restart: unless-stopped
    profiles:
      - production

volumes:
  huggingface_cache:
    driver: local

networks:
  default:
    name: ai-streaming-network